packages:
  - 'packages/*'
  - 'examples/*'
  - 'docs'
allowBuilds:
  better-sqlite3: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@super-line/client@0.4.0'
  - '@super-line/core@0.4.0'
  - '@super-line/react@0.4.0'
  - '@super-line/server@0.4.0'
  - '@super-line/transport-websocket@0.4.0'
  - '@super-line/client@0.5.0'
  - '@super-line/core@0.5.0'
  - '@super-line/server@0.5.0'
  - '@super-line/store-sync@0.5.1'
  - '@super-line/transport-websocket@0.5.0'
  - '@super-store/store@0.3.0'
  - '@super-line/react@0.5.0'
  - '@super-line/store-memory@0.5.0'
  - '@super-line/store-sqlite@0.1.0'
